ARG DATABASE_URL
ARG DIRECT_DATABASE_URL
ARG NODE_ENV=production

FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies

COPY package*.json ./
COPY admin/package*.json ./admin/

RUN npm install

# Bundle app source
COPY admin/ ./admin/
COPY packages/ ./packages/
COPY *.json ./

RUN npm run build -- --filter=admin

CMD [ "npm", "run", "start", "--", "--filter=admin" ]
