/* tslint:disable */

/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import { relations } from '@payloadcms/db-postgres/drizzle'
import {
  boolean,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgSchema,
  serial,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
  type AnyPgColumn
} from '@payloadcms/db-postgres/drizzle/pg-core'
export const db_schema = pgSchema('payload')
export const enum_books_contributions_tag = db_schema.enum(
  'enum_books_contributions_tag',
  ['Assistant']
)
export const enum_books_links_site = db_schema.enum('enum_books_links_site', [
  'Amazon',
  'Edelweiss+',
  'Bookshop.org',
  'Worldcat',
  'AbeBooks',
  'Other'
])
export const enum_books_status = db_schema.enum('enum_books_status', [
  'draft',
  'inReview',
  'published'
])
export const enum_books_source = db_schema.enum('enum_books_source', [
  'admin',
  'import',
  'submitted',
  'edelweiss'
])
export const enum_claims_state = db_schema.enum('enum_claims_state', [
  'pending',
  'approved',
  'cancelled'
])
export const enum_collections_status = db_schema.enum(
  'enum_collections_status',
  ['draft', 'inReview', 'published']
)
export const enum_memberships_role = db_schema.enum('enum_memberships_role', [
  'admin',
  'member'
])
export const enum_publisher_invitations_role = db_schema.enum(
  'enum_publisher_invitations_role',
  ['admin', 'member']
)
export const enum_users_role = db_schema.enum('enum_users_role', [
  'user',
  'admin',
  'waitlist'
])

export const accounts = db_schema.table(
  'accounts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    type: varchar('type').notNull(),
    provider: varchar('provider').notNull(),
    providerAccountId: varchar('provider_account_id').notNull(),
    refreshToken: varchar('refresh_token'),
    accessToken: varchar('access_token'),
    expiresAt: numeric('expires_at', { mode: 'number' }),
    tokenType: varchar('token_type'),
    scope: varchar('scope'),
    idToken: varchar('id_token'),
    sessionState: varchar('session_state'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('accounts_user_idx').on(columns.user),
    index('accounts_updated_at_idx').on(columns.updatedAt),
    index('accounts_created_at_idx').on(columns.createdAt),
    uniqueIndex('provider_providerAccountId_idx').on(
      columns.provider,
      columns.providerAccountId
    )
  ]
)

export const book_votes = db_schema.table(
  'book_votes',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    book: uuid('book_id')
      .notNull()
      .references(() => books.id, {
        onDelete: 'set null'
      }),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('book_votes_book_idx').on(columns.book),
    index('book_votes_user_idx').on(columns.user),
    index('book_votes_updated_at_idx').on(columns.updatedAt),
    index('book_votes_created_at_idx').on(columns.createdAt)
  ]
)

export const books_palette = db_schema.table(
  'books_palette',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    color: jsonb('color')
  },
  (columns) => [
    index('books_palette_order_idx').on(columns._order),
    index('books_palette_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [books.id],
      name: 'books_palette_parent_id_fk'
    }).onDelete('cascade')
  ]
)

export const books_contributions = db_schema.table(
  'books_contributions',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    profile: uuid('profile_id')
      .notNull()
      .references(() => profiles.id, {
        onDelete: 'set null'
      }),
    title: varchar('title'),
    job: uuid('job_id')
      .notNull()
      .references(() => jobs.id, {
        onDelete: 'set null'
      }),
    tag: enum_books_contributions_tag('tag')
  },
  (columns) => [
    index('books_contributions_order_idx').on(columns._order),
    index('books_contributions_parent_id_idx').on(columns._parentID),
    index('books_contributions_profile_idx').on(columns.profile),
    index('books_contributions_job_idx').on(columns.job),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [books.id],
      name: 'books_contributions_parent_id_fk'
    }).onDelete('cascade')
  ]
)

export const books_preview_images = db_schema.table(
  'books_preview_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id')
      .notNull()
      .references(() => images.id, {
        onDelete: 'set null'
      })
  },
  (columns) => [
    index('books_preview_images_order_idx').on(columns._order),
    index('books_preview_images_parent_id_idx').on(columns._parentID),
    index('books_preview_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [books.id],
      name: 'books_preview_images_parent_id_fk'
    }).onDelete('cascade')
  ]
)

export const books_links = db_schema.table(
  'books_links',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    url: varchar('url').notNull(),
    site: enum_books_links_site('site').notNull(),
    'site (other)': varchar('site_other')
  },
  (columns) => [
    index('books_links_order_idx').on(columns._order),
    index('books_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [books.id],
      name: 'books_links_parent_id_fk'
    }).onDelete('cascade')
  ]
)

export const books = db_schema.table(
  'books',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle'),
    slug: varchar('slug').notNull(),
    searchText: varchar('search_text'),
    status: enum_books_status('status').default('draft'),
    releaseDate: timestamp('release_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    pages: numeric('pages', { mode: 'number' }),
    blurb: varchar('blurb'),
    designCommentary: varchar('design_commentary'),
    source: enum_books_source('source').default('admin'),
    backgroundColor: jsonb('background_color'),
    googleBooksId: varchar('google_books_id'),
    publisher: uuid('publisher_id').references(() => publishers.id, {
      onDelete: 'set null'
    }),
    submitter: uuid('submitter_id').references(() => users.id, {
      onDelete: 'set null'
    }),
    coverImage: uuid('cover_image_id').references(() => images.id, {
      onDelete: 'set null'
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('books_slug_idx').on(columns.slug),
    index('books_search_text_idx').on(columns.searchText),
    index('books_publisher_idx').on(columns.publisher),
    index('books_submitter_idx').on(columns.submitter),
    index('books_cover_image_idx').on(columns.coverImage),
    index('books_updated_at_idx').on(columns.updatedAt),
    index('books_created_at_idx').on(columns.createdAt)
  ]
)

export const books_rels = db_schema.table(
  'books_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    profilesID: uuid('profiles_id'),
    tagsID: uuid('tags_id')
  },
  (columns) => [
    index('books_rels_order_idx').on(columns.order),
    index('books_rels_parent_idx').on(columns.parent),
    index('books_rels_path_idx').on(columns.path),
    index('books_rels_profiles_id_idx').on(columns.profilesID),
    index('books_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [books.id],
      name: 'books_rels_parent_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['profilesID']],
      foreignColumns: [profiles.id],
      name: 'books_rels_profiles_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'books_rels_tags_fk'
    }).onDelete('cascade')
  ]
)

export const claims = db_schema.table(
  'claims',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    profile: uuid('profile_id')
      .notNull()
      .references(() => profiles.id, {
        onDelete: 'set null'
      }),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    secret: varchar('secret').notNull(),
    approvedAt: timestamp('approved_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    cancelledAt: timestamp('cancelled_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    state: enum_claims_state('state').default('pending'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('claims_profile_idx').on(columns.profile),
    index('claims_user_idx').on(columns.user),
    index('claims_updated_at_idx').on(columns.updatedAt),
    index('claims_created_at_idx').on(columns.createdAt)
  ]
)

export const collections = db_schema.table(
  'collections',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    status: enum_collections_status('status').default('draft'),
    publisher: uuid('publisher_id').references(() => publishers.id, {
      onDelete: 'set null'
    }),
    bookshopDotOrgUrl: varchar('bookshop_dot_org_url'),
    publisherFeatured: boolean('publisher_featured').default(false),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('collections_slug_idx').on(columns.slug),
    index('collections_publisher_idx').on(columns.publisher),
    index('collections_updated_at_idx').on(columns.updatedAt),
    index('collections_created_at_idx').on(columns.createdAt)
  ]
)

export const collections_rels = db_schema.table(
  'collections_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    booksID: uuid('books_id')
  },
  (columns) => [
    index('collections_rels_order_idx').on(columns.order),
    index('collections_rels_parent_idx').on(columns.parent),
    index('collections_rels_path_idx').on(columns.path),
    index('collections_rels_books_id_idx').on(columns.booksID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [collections.id],
      name: 'collections_rels_parent_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['booksID']],
      foreignColumns: [books.id],
      name: 'collections_rels_books_fk'
    }).onDelete('cascade')
  ]
)

export const faqs = db_schema.table(
  'faqs',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    _order: varchar('_order'),
    question: varchar('question').notNull(),
    answer: jsonb('answer'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('faqs__order_idx').on(columns._order),
    uniqueIndex('faqs_question_idx').on(columns.question),
    index('faqs_updated_at_idx').on(columns.updatedAt),
    index('faqs_created_at_idx').on(columns.createdAt)
  ]
)

export const favourites = db_schema.table(
  'favourites',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    profile: uuid('profile_id')
      .notNull()
      .references(() => profiles.id, {
        onDelete: 'set null'
      }),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('favourites_profile_idx').on(columns.profile),
    index('favourites_user_idx').on(columns.user),
    index('favourites_updated_at_idx').on(columns.updatedAt),
    index('favourites_created_at_idx').on(columns.createdAt)
  ]
)

export const featured_profiles = db_schema.table(
  'featured_profiles',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    _order: varchar('_order'),
    profile: uuid('profile_id')
      .notNull()
      .references(() => profiles.id, {
        onDelete: 'set null'
      }),
    until: timestamp('until', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('featured_profiles__order_idx').on(columns._order),
    index('featured_profiles_profile_idx').on(columns.profile),
    index('featured_profiles_updated_at_idx').on(columns.updatedAt),
    index('featured_profiles_created_at_idx').on(columns.createdAt)
  ]
)

export const features = db_schema.table(
  'features',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    _order: varchar('_order'),
    book: uuid('book_id')
      .notNull()
      .references(() => books.id, {
        onDelete: 'set null'
      }),
    tagLine: varchar('tag_line'),
    until: timestamp('until', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('features__order_idx').on(columns._order),
    index('features_book_idx').on(columns.book),
    index('features_updated_at_idx').on(columns.updatedAt),
    index('features_created_at_idx').on(columns.createdAt)
  ]
)

export const images = db_schema.table(
  'images',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    placeholderUrl: varchar('placeholder_url'),
    prefix: varchar('prefix').default('payload'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_blurPlaceholder_url: varchar('sizes_blur_placeholder_url'),
    sizes_blurPlaceholder_width: numeric('sizes_blur_placeholder_width', {
      mode: 'number'
    }),
    sizes_blurPlaceholder_height: numeric('sizes_blur_placeholder_height', {
      mode: 'number'
    }),
    sizes_blurPlaceholder_mimeType: varchar('sizes_blur_placeholder_mime_type'),
    sizes_blurPlaceholder_filesize: numeric('sizes_blur_placeholder_filesize', {
      mode: 'number'
    }),
    sizes_blurPlaceholder_filename: varchar('sizes_blur_placeholder_filename')
  },
  (columns) => [
    index('images_updated_at_idx').on(columns.updatedAt),
    index('images_created_at_idx').on(columns.createdAt),
    uniqueIndex('images_filename_idx').on(columns.filename),
    index('images_sizes_blur_placeholder_sizes_blur_placeholder_fil_idx').on(
      columns.sizes_blurPlaceholder_filename
    )
  ]
)

export const jobs = db_schema.table(
  'jobs',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    featured: boolean('featured').default(true),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('jobs_name_idx').on(columns.name),
    index('jobs_updated_at_idx').on(columns.updatedAt),
    index('jobs_created_at_idx').on(columns.createdAt)
  ]
)

export const locations = db_schema.table(
  'locations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    placeId: varchar('place_id').notNull(),
    displayText: varchar('display_text').notNull(),
    slug: varchar('slug').notNull(),
    country: varchar('country'),
    region: varchar('region'),
    latitude: numeric('latitude', { mode: 'number' }).notNull(),
    longitude: numeric('longitude', { mode: 'number' }).notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('locations_place_id_idx').on(columns.placeId),
    uniqueIndex('locations_slug_idx').on(columns.slug),
    index('locations_updated_at_idx').on(columns.updatedAt),
    index('locations_created_at_idx').on(columns.createdAt)
  ]
)

export const memberships = db_schema.table(
  'memberships',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    publisher: uuid('publisher_id')
      .notNull()
      .references(() => publishers.id, {
        onDelete: 'set null'
      }),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    role: enum_memberships_role('role').notNull().default('member'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('memberships_publisher_idx').on(columns.publisher),
    index('memberships_user_idx').on(columns.user),
    index('memberships_updated_at_idx').on(columns.updatedAt),
    index('memberships_created_at_idx').on(columns.createdAt)
  ]
)

export const pitches = db_schema.table(
  'pitches',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    author: uuid('author_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    description: varchar('description').notNull(),
    viewCount: numeric('view_count', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('pitches_author_idx').on(columns.author),
    index('pitches_updated_at_idx').on(columns.updatedAt),
    index('pitches_created_at_idx').on(columns.createdAt)
  ]
)

export const posts = db_schema.table(
  'posts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    content: jsonb('content').notNull(),
    author: uuid('author_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    publishAt: timestamp('publish_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug),
    index('posts_author_idx').on(columns.author),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt)
  ]
)

export const posts_rels = db_schema.table(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    imagesID: uuid('images_id')
  },
  (columns) => [
    index('posts_rels_order_idx').on(columns.order),
    index('posts_rels_parent_idx').on(columns.parent),
    index('posts_rels_path_idx').on(columns.path),
    index('posts_rels_images_id_idx').on(columns.imagesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['imagesID']],
      foreignColumns: [images.id],
      name: 'posts_rels_images_fk'
    }).onDelete('cascade')
  ]
)

export const profiles = db_schema.table(
  'profiles',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    avatar: uuid('avatar_id').references(() => images.id, {
      onDelete: 'set null'
    }),
    description: varchar('description'),
    jobTitle: varchar('job_title'),
    location: varchar('location'),
    website: varchar('website'),
    instagram: varchar('instagram'),
    mostRecentlyPublishedOn: timestamp('most_recently_published_on', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    user: uuid('user_id').references(() => users.id, {
      onDelete: 'set null'
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('profiles_slug_idx').on(columns.slug),
    index('profiles_avatar_idx').on(columns.avatar),
    index('profiles_user_idx').on(columns.user),
    index('profiles_updated_at_idx').on(columns.updatedAt),
    index('profiles_created_at_idx').on(columns.createdAt)
  ]
)

export const profiles_rels = db_schema.table(
  'profiles_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    locationsID: uuid('locations_id'),
    profilesID: uuid('profiles_id')
  },
  (columns) => [
    index('profiles_rels_order_idx').on(columns.order),
    index('profiles_rels_parent_idx').on(columns.parent),
    index('profiles_rels_path_idx').on(columns.path),
    index('profiles_rels_locations_id_idx').on(columns.locationsID),
    index('profiles_rels_profiles_id_idx').on(columns.profilesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [profiles.id],
      name: 'profiles_rels_parent_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['locationsID']],
      foreignColumns: [locations.id],
      name: 'profiles_rels_locations_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['profilesID']],
      foreignColumns: [profiles.id],
      name: 'profiles_rels_profiles_fk'
    }).onDelete('cascade')
  ]
)

export const publisher_invitations = db_schema.table(
  'publisher_invitations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    email: varchar('email').notNull(),
    publisher: uuid('publisher_id')
      .notNull()
      .references(() => publishers.id, {
        onDelete: 'set null'
      }),
    invitedBy: uuid('invited_by_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null'
      }),
    role: enum_publisher_invitations_role('role').notNull().default('member'),
    acceptedAt: timestamp('accepted_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('publisher_invitations_publisher_idx').on(columns.publisher),
    index('publisher_invitations_invited_by_idx').on(columns.invitedBy),
    index('publisher_invitations_updated_at_idx').on(columns.updatedAt),
    index('publisher_invitations_created_at_idx').on(columns.createdAt)
  ]
)

export const publishers = db_schema.table(
  'publishers',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    logo: uuid('logo_id').references(() => images.id, {
      onDelete: 'set null'
    }),
    description: varchar('description'),
    website: varchar('website'),
    instagram: varchar('instagram'),
    genericContact: varchar('generic_contact'),
    directContact: varchar('direct_contact'),
    house: uuid('house_id').references((): AnyPgColumn => publishers.id, {
      onDelete: 'set null'
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('publishers_name_idx').on(columns.name),
    uniqueIndex('publishers_slug_idx').on(columns.slug),
    index('publishers_logo_idx').on(columns.logo),
    index('publishers_house_idx').on(columns.house),
    index('publishers_updated_at_idx').on(columns.updatedAt),
    index('publishers_created_at_idx').on(columns.createdAt)
  ]
)

export const publishers_rels = db_schema.table(
  'publishers_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    booksID: uuid('books_id')
  },
  (columns) => [
    index('publishers_rels_order_idx').on(columns.order),
    index('publishers_rels_parent_idx').on(columns.parent),
    index('publishers_rels_path_idx').on(columns.path),
    index('publishers_rels_books_id_idx').on(columns.booksID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [publishers.id],
      name: 'publishers_rels_parent_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['booksID']],
      foreignColumns: [books.id],
      name: 'publishers_rels_books_fk'
    }).onDelete('cascade')
  ]
)

export const tag_groups = db_schema.table(
  'tag_groups',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    adminOnly: boolean('admin_only').default(false),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('tag_groups_name_idx').on(columns.name),
    uniqueIndex('tag_groups_slug_idx').on(columns.slug),
    index('tag_groups_updated_at_idx').on(columns.updatedAt),
    index('tag_groups_created_at_idx').on(columns.createdAt)
  ]
)

export const tags = db_schema.table(
  'tags',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    group: uuid('group_id')
      .notNull()
      .references(() => tag_groups.id, {
        onDelete: 'set null'
      }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('tags_name_idx').on(columns.name),
    uniqueIndex('tags_slug_idx').on(columns.slug),
    index('tags_group_idx').on(columns.group),
    index('tags_updated_at_idx').on(columns.updatedAt),
    index('tags_created_at_idx').on(columns.createdAt)
  ]
)

export const users = db_schema.table(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    email: varchar('email').notNull(),
    name: varchar('name'),
    role: enum_users_role('role').default('user'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('users_email_idx').on(columns.email),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt)
  ]
)

export const verification_tokens = db_schema.table(
  'verification_tokens',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    identifier: varchar('identifier').notNull(),
    token: varchar('token').notNull(),
    expires: timestamp('expires', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }).notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    uniqueIndex('verification_tokens_token_idx').on(columns.token),
    index('verification_tokens_updated_at_idx').on(columns.updatedAt),
    index('verification_tokens_created_at_idx').on(columns.createdAt),
    uniqueIndex('identifier_token_idx').on(columns.identifier, columns.token)
  ]
)

export const payload_kv = db_schema.table(
  'payload_kv',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull()
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)]
)

export const payload_locked_documents = db_schema.table(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt)
  ]
)

export const payload_locked_documents_rels = db_schema.table(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    accountsID: uuid('accounts_id'),
    'book-votesID': uuid('book_votes_id'),
    booksID: uuid('books_id'),
    claimsID: uuid('claims_id'),
    collectionsID: uuid('collections_id'),
    faqsID: uuid('faqs_id'),
    favouritesID: uuid('favourites_id'),
    'featured-profilesID': uuid('featured_profiles_id'),
    featuresID: uuid('features_id'),
    imagesID: uuid('images_id'),
    jobsID: uuid('jobs_id'),
    locationsID: uuid('locations_id'),
    membershipsID: uuid('memberships_id'),
    pitchesID: uuid('pitches_id'),
    postsID: uuid('posts_id'),
    profilesID: uuid('profiles_id'),
    'publisher-invitationsID': uuid('publisher_invitations_id'),
    publishersID: uuid('publishers_id'),
    'tag-groupsID': uuid('tag_groups_id'),
    tagsID: uuid('tags_id'),
    usersID: uuid('users_id'),
    'verification-tokensID': uuid('verification_tokens_id')
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_accounts_id_idx').on(
      columns.accountsID
    ),
    index('payload_locked_documents_rels_book_votes_id_idx').on(
      columns['book-votesID']
    ),
    index('payload_locked_documents_rels_books_id_idx').on(columns.booksID),
    index('payload_locked_documents_rels_claims_id_idx').on(columns.claimsID),
    index('payload_locked_documents_rels_collections_id_idx').on(
      columns.collectionsID
    ),
    index('payload_locked_documents_rels_faqs_id_idx').on(columns.faqsID),
    index('payload_locked_documents_rels_favourites_id_idx').on(
      columns.favouritesID
    ),
    index('payload_locked_documents_rels_featured_profiles_id_idx').on(
      columns['featured-profilesID']
    ),
    index('payload_locked_documents_rels_features_id_idx').on(
      columns.featuresID
    ),
    index('payload_locked_documents_rels_images_id_idx').on(columns.imagesID),
    index('payload_locked_documents_rels_jobs_id_idx').on(columns.jobsID),
    index('payload_locked_documents_rels_locations_id_idx').on(
      columns.locationsID
    ),
    index('payload_locked_documents_rels_memberships_id_idx').on(
      columns.membershipsID
    ),
    index('payload_locked_documents_rels_pitches_id_idx').on(columns.pitchesID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_profiles_id_idx').on(
      columns.profilesID
    ),
    index('payload_locked_documents_rels_publisher_invitations_id_idx').on(
      columns['publisher-invitationsID']
    ),
    index('payload_locked_documents_rels_publishers_id_idx').on(
      columns.publishersID
    ),
    index('payload_locked_documents_rels_tag_groups_id_idx').on(
      columns['tag-groupsID']
    ),
    index('payload_locked_documents_rels_tags_id_idx').on(columns.tagsID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_verification_tokens_id_idx').on(
      columns['verification-tokensID']
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['accountsID']],
      foreignColumns: [accounts.id],
      name: 'payload_locked_documents_rels_accounts_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['book-votesID']],
      foreignColumns: [book_votes.id],
      name: 'payload_locked_documents_rels_book_votes_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['booksID']],
      foreignColumns: [books.id],
      name: 'payload_locked_documents_rels_books_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['claimsID']],
      foreignColumns: [claims.id],
      name: 'payload_locked_documents_rels_claims_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['collectionsID']],
      foreignColumns: [collections.id],
      name: 'payload_locked_documents_rels_collections_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'payload_locked_documents_rels_faqs_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['favouritesID']],
      foreignColumns: [favourites.id],
      name: 'payload_locked_documents_rels_favourites_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['featured-profilesID']],
      foreignColumns: [featured_profiles.id],
      name: 'payload_locked_documents_rels_featured_profiles_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['featuresID']],
      foreignColumns: [features.id],
      name: 'payload_locked_documents_rels_features_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['imagesID']],
      foreignColumns: [images.id],
      name: 'payload_locked_documents_rels_images_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['jobsID']],
      foreignColumns: [jobs.id],
      name: 'payload_locked_documents_rels_jobs_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['locationsID']],
      foreignColumns: [locations.id],
      name: 'payload_locked_documents_rels_locations_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['membershipsID']],
      foreignColumns: [memberships.id],
      name: 'payload_locked_documents_rels_memberships_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pitchesID']],
      foreignColumns: [pitches.id],
      name: 'payload_locked_documents_rels_pitches_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['profilesID']],
      foreignColumns: [profiles.id],
      name: 'payload_locked_documents_rels_profiles_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['publisher-invitationsID']],
      foreignColumns: [publisher_invitations.id],
      name: 'payload_locked_documents_rels_publisher_invitations_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['publishersID']],
      foreignColumns: [publishers.id],
      name: 'payload_locked_documents_rels_publishers_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tag-groupsID']],
      foreignColumns: [tag_groups.id],
      name: 'payload_locked_documents_rels_tag_groups_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['verification-tokensID']],
      foreignColumns: [verification_tokens.id],
      name: 'payload_locked_documents_rels_verification_tokens_fk'
    }).onDelete('cascade')
  ]
)

export const payload_preferences = db_schema.table(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt)
  ]
)

export const payload_preferences_rels = db_schema.table(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id')
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade')
  ]
)

export const payload_migrations = db_schema.table(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    })
      .defaultNow()
      .notNull()
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt)
  ]
)

export const relations_accounts = relations(accounts, ({ one }) => ({
  user: one(users, {
    fields: [accounts.user],
    references: [users.id],
    relationName: 'user'
  })
}))
export const relations_book_votes = relations(book_votes, ({ one }) => ({
  book: one(books, {
    fields: [book_votes.book],
    references: [books.id],
    relationName: 'book'
  }),
  user: one(users, {
    fields: [book_votes.user],
    references: [users.id],
    relationName: 'user'
  })
}))
export const relations_books_palette = relations(books_palette, ({ one }) => ({
  _parentID: one(books, {
    fields: [books_palette._parentID],
    references: [books.id],
    relationName: 'palette'
  })
}))
export const relations_books_contributions = relations(
  books_contributions,
  ({ one }) => ({
    _parentID: one(books, {
      fields: [books_contributions._parentID],
      references: [books.id],
      relationName: 'contributions'
    }),
    profile: one(profiles, {
      fields: [books_contributions.profile],
      references: [profiles.id],
      relationName: 'profile'
    }),
    job: one(jobs, {
      fields: [books_contributions.job],
      references: [jobs.id],
      relationName: 'job'
    })
  })
)
export const relations_books_preview_images = relations(
  books_preview_images,
  ({ one }) => ({
    _parentID: one(books, {
      fields: [books_preview_images._parentID],
      references: [books.id],
      relationName: 'previewImages'
    }),
    image: one(images, {
      fields: [books_preview_images.image],
      references: [images.id],
      relationName: 'image'
    })
  })
)
export const relations_books_links = relations(books_links, ({ one }) => ({
  _parentID: one(books, {
    fields: [books_links._parentID],
    references: [books.id],
    relationName: 'links'
  })
}))
export const relations_books_rels = relations(books_rels, ({ one }) => ({
  parent: one(books, {
    fields: [books_rels.parent],
    references: [books.id],
    relationName: '_rels'
  }),
  profilesID: one(profiles, {
    fields: [books_rels.profilesID],
    references: [profiles.id],
    relationName: 'profiles'
  }),
  tagsID: one(tags, {
    fields: [books_rels.tagsID],
    references: [tags.id],
    relationName: 'tags'
  })
}))
export const relations_books = relations(books, ({ one, many }) => ({
  palette: many(books_palette, {
    relationName: 'palette'
  }),
  publisher: one(publishers, {
    fields: [books.publisher],
    references: [publishers.id],
    relationName: 'publisher'
  }),
  submitter: one(users, {
    fields: [books.submitter],
    references: [users.id],
    relationName: 'submitter'
  }),
  contributions: many(books_contributions, {
    relationName: 'contributions'
  }),
  coverImage: one(images, {
    fields: [books.coverImage],
    references: [images.id],
    relationName: 'coverImage'
  }),
  previewImages: many(books_preview_images, {
    relationName: 'previewImages'
  }),
  links: many(books_links, {
    relationName: 'links'
  }),
  _rels: many(books_rels, {
    relationName: '_rels'
  })
}))
export const relations_claims = relations(claims, ({ one }) => ({
  profile: one(profiles, {
    fields: [claims.profile],
    references: [profiles.id],
    relationName: 'profile'
  }),
  user: one(users, {
    fields: [claims.user],
    references: [users.id],
    relationName: 'user'
  })
}))
export const relations_collections_rels = relations(
  collections_rels,
  ({ one }) => ({
    parent: one(collections, {
      fields: [collections_rels.parent],
      references: [collections.id],
      relationName: '_rels'
    }),
    booksID: one(books, {
      fields: [collections_rels.booksID],
      references: [books.id],
      relationName: 'books'
    })
  })
)
export const relations_collections = relations(
  collections,
  ({ one, many }) => ({
    publisher: one(publishers, {
      fields: [collections.publisher],
      references: [publishers.id],
      relationName: 'publisher'
    }),
    _rels: many(collections_rels, {
      relationName: '_rels'
    })
  })
)
export const relations_faqs = relations(faqs, () => ({}))
export const relations_favourites = relations(favourites, ({ one }) => ({
  profile: one(profiles, {
    fields: [favourites.profile],
    references: [profiles.id],
    relationName: 'profile'
  }),
  user: one(users, {
    fields: [favourites.user],
    references: [users.id],
    relationName: 'user'
  })
}))
export const relations_featured_profiles = relations(
  featured_profiles,
  ({ one }) => ({
    profile: one(profiles, {
      fields: [featured_profiles.profile],
      references: [profiles.id],
      relationName: 'profile'
    })
  })
)
export const relations_features = relations(features, ({ one }) => ({
  book: one(books, {
    fields: [features.book],
    references: [books.id],
    relationName: 'book'
  })
}))
export const relations_images = relations(images, () => ({}))
export const relations_jobs = relations(jobs, () => ({}))
export const relations_locations = relations(locations, () => ({}))
export const relations_memberships = relations(memberships, ({ one }) => ({
  publisher: one(publishers, {
    fields: [memberships.publisher],
    references: [publishers.id],
    relationName: 'publisher'
  }),
  user: one(users, {
    fields: [memberships.user],
    references: [users.id],
    relationName: 'user'
  })
}))
export const relations_pitches = relations(pitches, ({ one }) => ({
  author: one(users, {
    fields: [pitches.author],
    references: [users.id],
    relationName: 'author'
  })
}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels'
  }),
  imagesID: one(images, {
    fields: [posts_rels.imagesID],
    references: [images.id],
    relationName: 'images'
  })
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  author: one(users, {
    fields: [posts.author],
    references: [users.id],
    relationName: 'author'
  }),
  _rels: many(posts_rels, {
    relationName: '_rels'
  })
}))
export const relations_profiles_rels = relations(profiles_rels, ({ one }) => ({
  parent: one(profiles, {
    fields: [profiles_rels.parent],
    references: [profiles.id],
    relationName: '_rels'
  }),
  locationsID: one(locations, {
    fields: [profiles_rels.locationsID],
    references: [locations.id],
    relationName: 'locations'
  }),
  profilesID: one(profiles, {
    fields: [profiles_rels.profilesID],
    references: [profiles.id],
    relationName: 'profiles'
  })
}))
export const relations_profiles = relations(profiles, ({ one, many }) => ({
  avatar: one(images, {
    fields: [profiles.avatar],
    references: [images.id],
    relationName: 'avatar'
  }),
  user: one(users, {
    fields: [profiles.user],
    references: [users.id],
    relationName: 'user'
  }),
  _rels: many(profiles_rels, {
    relationName: '_rels'
  })
}))
export const relations_publisher_invitations = relations(
  publisher_invitations,
  ({ one }) => ({
    publisher: one(publishers, {
      fields: [publisher_invitations.publisher],
      references: [publishers.id],
      relationName: 'publisher'
    }),
    invitedBy: one(users, {
      fields: [publisher_invitations.invitedBy],
      references: [users.id],
      relationName: 'invitedBy'
    })
  })
)
export const relations_publishers_rels = relations(
  publishers_rels,
  ({ one }) => ({
    parent: one(publishers, {
      fields: [publishers_rels.parent],
      references: [publishers.id],
      relationName: '_rels'
    }),
    booksID: one(books, {
      fields: [publishers_rels.booksID],
      references: [books.id],
      relationName: 'books'
    })
  })
)
export const relations_publishers = relations(publishers, ({ one, many }) => ({
  logo: one(images, {
    fields: [publishers.logo],
    references: [images.id],
    relationName: 'logo'
  }),
  house: one(publishers, {
    fields: [publishers.house],
    references: [publishers.id],
    relationName: 'house'
  }),
  _rels: many(publishers_rels, {
    relationName: '_rels'
  })
}))
export const relations_tag_groups = relations(tag_groups, () => ({}))
export const relations_tags = relations(tags, ({ one }) => ({
  group: one(tag_groups, {
    fields: [tags.group],
    references: [tag_groups.id],
    relationName: 'group'
  })
}))
export const relations_users = relations(users, () => ({}))
export const relations_verification_tokens = relations(
  verification_tokens,
  () => ({})
)
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels'
    }),
    accountsID: one(accounts, {
      fields: [payload_locked_documents_rels.accountsID],
      references: [accounts.id],
      relationName: 'accounts'
    }),
    'book-votesID': one(book_votes, {
      fields: [payload_locked_documents_rels['book-votesID']],
      references: [book_votes.id],
      relationName: 'book-votes'
    }),
    booksID: one(books, {
      fields: [payload_locked_documents_rels.booksID],
      references: [books.id],
      relationName: 'books'
    }),
    claimsID: one(claims, {
      fields: [payload_locked_documents_rels.claimsID],
      references: [claims.id],
      relationName: 'claims'
    }),
    collectionsID: one(collections, {
      fields: [payload_locked_documents_rels.collectionsID],
      references: [collections.id],
      relationName: 'collections'
    }),
    faqsID: one(faqs, {
      fields: [payload_locked_documents_rels.faqsID],
      references: [faqs.id],
      relationName: 'faqs'
    }),
    favouritesID: one(favourites, {
      fields: [payload_locked_documents_rels.favouritesID],
      references: [favourites.id],
      relationName: 'favourites'
    }),
    'featured-profilesID': one(featured_profiles, {
      fields: [payload_locked_documents_rels['featured-profilesID']],
      references: [featured_profiles.id],
      relationName: 'featured-profiles'
    }),
    featuresID: one(features, {
      fields: [payload_locked_documents_rels.featuresID],
      references: [features.id],
      relationName: 'features'
    }),
    imagesID: one(images, {
      fields: [payload_locked_documents_rels.imagesID],
      references: [images.id],
      relationName: 'images'
    }),
    jobsID: one(jobs, {
      fields: [payload_locked_documents_rels.jobsID],
      references: [jobs.id],
      relationName: 'jobs'
    }),
    locationsID: one(locations, {
      fields: [payload_locked_documents_rels.locationsID],
      references: [locations.id],
      relationName: 'locations'
    }),
    membershipsID: one(memberships, {
      fields: [payload_locked_documents_rels.membershipsID],
      references: [memberships.id],
      relationName: 'memberships'
    }),
    pitchesID: one(pitches, {
      fields: [payload_locked_documents_rels.pitchesID],
      references: [pitches.id],
      relationName: 'pitches'
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts'
    }),
    profilesID: one(profiles, {
      fields: [payload_locked_documents_rels.profilesID],
      references: [profiles.id],
      relationName: 'profiles'
    }),
    'publisher-invitationsID': one(publisher_invitations, {
      fields: [payload_locked_documents_rels['publisher-invitationsID']],
      references: [publisher_invitations.id],
      relationName: 'publisher-invitations'
    }),
    publishersID: one(publishers, {
      fields: [payload_locked_documents_rels.publishersID],
      references: [publishers.id],
      relationName: 'publishers'
    }),
    'tag-groupsID': one(tag_groups, {
      fields: [payload_locked_documents_rels['tag-groupsID']],
      references: [tag_groups.id],
      relationName: 'tag-groups'
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags'
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users'
    }),
    'verification-tokensID': one(verification_tokens, {
      fields: [payload_locked_documents_rels['verification-tokensID']],
      references: [verification_tokens.id],
      relationName: 'verification-tokens'
    })
  })
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels'
    })
  })
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels'
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users'
    })
  })
)
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: '_rels'
    })
  })
)
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({})
)

type DatabaseSchema = {
  db_schema: typeof db_schema
  enum_books_contributions_tag: typeof enum_books_contributions_tag
  enum_books_links_site: typeof enum_books_links_site
  enum_books_status: typeof enum_books_status
  enum_books_source: typeof enum_books_source
  enum_claims_state: typeof enum_claims_state
  enum_collections_status: typeof enum_collections_status
  enum_memberships_role: typeof enum_memberships_role
  enum_publisher_invitations_role: typeof enum_publisher_invitations_role
  enum_users_role: typeof enum_users_role
  accounts: typeof accounts
  book_votes: typeof book_votes
  books_palette: typeof books_palette
  books_contributions: typeof books_contributions
  books_preview_images: typeof books_preview_images
  books_links: typeof books_links
  books: typeof books
  books_rels: typeof books_rels
  claims: typeof claims
  collections: typeof collections
  collections_rels: typeof collections_rels
  faqs: typeof faqs
  favourites: typeof favourites
  featured_profiles: typeof featured_profiles
  features: typeof features
  images: typeof images
  jobs: typeof jobs
  locations: typeof locations
  memberships: typeof memberships
  pitches: typeof pitches
  posts: typeof posts
  posts_rels: typeof posts_rels
  profiles: typeof profiles
  profiles_rels: typeof profiles_rels
  publisher_invitations: typeof publisher_invitations
  publishers: typeof publishers
  publishers_rels: typeof publishers_rels
  tag_groups: typeof tag_groups
  tags: typeof tags
  users: typeof users
  verification_tokens: typeof verification_tokens
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_accounts: typeof relations_accounts
  relations_book_votes: typeof relations_book_votes
  relations_books_palette: typeof relations_books_palette
  relations_books_contributions: typeof relations_books_contributions
  relations_books_preview_images: typeof relations_books_preview_images
  relations_books_links: typeof relations_books_links
  relations_books_rels: typeof relations_books_rels
  relations_books: typeof relations_books
  relations_claims: typeof relations_claims
  relations_collections_rels: typeof relations_collections_rels
  relations_collections: typeof relations_collections
  relations_faqs: typeof relations_faqs
  relations_favourites: typeof relations_favourites
  relations_featured_profiles: typeof relations_featured_profiles
  relations_features: typeof relations_features
  relations_images: typeof relations_images
  relations_jobs: typeof relations_jobs
  relations_locations: typeof relations_locations
  relations_memberships: typeof relations_memberships
  relations_pitches: typeof relations_pitches
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations_profiles_rels: typeof relations_profiles_rels
  relations_profiles: typeof relations_profiles
  relations_publisher_invitations: typeof relations_publisher_invitations
  relations_publishers_rels: typeof relations_publishers_rels
  relations_publishers: typeof relations_publishers
  relations_tag_groups: typeof relations_tag_groups
  relations_tags: typeof relations_tags
  relations_users: typeof relations_users
  relations_verification_tokens: typeof relations_verification_tokens
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
